# wrangler.toml
name = "llmmatcher"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "llmmatcher-votes"
database_id = "69968357-1715-4e3a-8f16-cc6dffba6a8c"

[[kv_namespaces]]
binding = "VOTE_RATE"
id = "987790992a554d0c907770e224e8935a"

[[kv_namespaces]]
binding = "SUBSCRIBERS"
id = "c6f608fe8ec74b6383e6f9289c62936b"
